Buy Order Agent
6-Billionaires/trading-agent pull request #9
Opened 2018-08-16 11:22 UTC by onmylife

1. 랜덤 시점에 대해서 y값을 구해서 pickle를 생성하는 것
2. 모든 시점(120초)에 대해서 y값을 구해서 pickle 생성하는 것
   - 거의 면적에 준함
   - 리팩토링 했으니, 타 에이전트에서 피클 생성을 빠르게 할 필요가 있으면 참고하면 좋을 듯
3. train은 build network에서 실패 - 억사마 구조 요청 
4. 피클 파일은 너무 용량이 커서 업로드 불가로 gitignore에 추가해 놓음
   테스트하실분은 돌리시면 오래지않아 피클 생성 될꺼에요

2018-08-17 03:47 UTC, verystrongjoe commented
어제 회의에 나온것  반영시까지 보류! @onmylife 
1  X(경과시간, 체결/호가 정보의 Observations) -> Y(Price of Signal - Price of min) 기준 pickle 재 생성
2. train.py 도 정의해서 다시 알려주세요  network 다시 짜드립니다.

2018-08-22 01:10 UTC, onmylife commented
/pickle_maker_min_price.py로 max_secs(90초) 동안 최소값을 기준으로 y밸류 및 시간 구하는 걸로 새로 만들어서 pickle도 떨궈놨어요.
@verystrongjoe 네트워크 생성 부탁해요

2018-08-22 12:29 UTC, verystrongjoe requested changes
get_real_data()함수로 리턴이 feature라는걸 추가하고  build_network으로 인자 전달하는데  get_real_data에는 리턴을 안하고 있구요.  무슨 이유인지?

그리고 build network의 경우에도 기존 네트워크에서 추가로 buy order agent특성상 남은시간만 들어가면 되는건가요?  우선 생성을 하는데 어떻게 구성할지 말씀을 해주셔야 제가 그대로 구현을 하든지 할텐데요. X,Y에 대한 설명이라도 언급해주세요~~

2018-08-22 12:29 UTC, verystrongjoe commented on buy_order_agent/seungho/pickle_maker.py
> +def prepare_datasets(max_secs=60):
여기가 60초인게 아니라 1분 30초여야 될텐데??!

2018-08-22 12:29 UTC, verystrongjoe commented on buy_order_agent/seungho/pickle_maker_min_price.py
> +def prepare_datasets(max_secs=90):
여긴 또 90초네요?

2018-08-22 12:32 UTC, verystrongjoe commented
buy_order_agent/seungho/pickle_maker_max_secs.py 와 buy_order_agent/seungho/pickle_maker_min_price.py 의 차이가??  우선 min녀석으로만 pickle이 생성이 되어있네요.

2018-08-22 12:58 UTC, verystrongjoe commented
pickle.dump([x_2d, x_1d, x_min_secs, y_1d], f) 아 여기에서 min_secs를 받아오는 군요 네트워크 부분 제가 업데이트 햇습니다. 이 브랜치에 commit했으니 pull해서 이어서 작업하시면 되겠습니다.

2018-08-22 12:58 UTC, onmylife commented on buy_order_agent/seungho/pickle_maker.py
> +def prepare_datasets(max_secs=60):
피클은 테스트 데이터고 시간은 디폴트값이니까 필요에 따라 바꾸면 됩니다. 저번 회의때 왔다갔다 해서 헤깔리네요

2018-08-22 12:58 UTC, onmylife commented on buy_order_agent/seungho/pickle_maker.py
> +def prepare_datasets(max_secs=60):
피클은 테스트 데이터고 시간은 디폴트값이니까 필요에 따라 바꾸면 됩니다. 저번 회의때 왔다갔다 해서 헤깔리네요

2018-09-09 01:30 UTC, closed without merging